[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  COMPARI5_BASE_URL = "https://legendary-griffin-ca6898.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = [".data/**"]
